# Generated by Django 5.0.7 on 2024-07-21 18:27

import django.db.models.deletion
import recipe.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Groceries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grocery', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('serving_size', models.IntegerField()),
                ('cooking_time', models.DurationField()),
                ('ingredients', models.TextField()),
                ('directions', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(default=recipe.models.get_default_course, on_delete=django.db.models.deletion.CASCADE, to='recipe.courses')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeNutrtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField()),
                ('total_fat', models.FloatField()),
                ('saturated_fat', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('total_carbohydrate', models.FloatField()),
                ('dietary_fiber', models.FloatField()),
                ('sugars', models.FloatField()),
                ('protien', models.FloatField()),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
            ],
        ),
    ]
