# Generated by Django 5.0.7 on 2024-07-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeNutrtion',
        ),
    ]
