# Generated by Django 5.0.7 on 2024-07-21 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipenutrtion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipenutrtion',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutrition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipenutrtion'),
        ),
    ]
