# Generated by Django 5.0.7 on 2024-07-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='course',
            new_name='courses',
        ),
    ]
