# Generated by Django 5.0.7 on 2024-07-20 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_rename_course_recipe_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='courses',
            new_name='course',
        ),
    ]
