# Generated by Django 5.0.7 on 2024-07-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_remove_recipe_nutrition_recipenutrtion_recipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeNutrtion',
            new_name='RecipeNutrition',
        ),
    ]
