# Generated by Django 5.0.7 on 2024-07-20 18:18

import django.db.models.deletion
import recipe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_alter_recipe_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='course',
            field=models.ForeignKey(default=recipe.models.get_default_course, on_delete=django.db.models.deletion.CASCADE, to='recipe.courses'),
        ),
    ]
