# Generated by Django 5.0.7 on 2024-07-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_rename_recipenutrtion_recipenutrition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.DurationField(null=True),
        ),
    ]
