# Generated by Django 5.0.7 on 2024-07-22 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipenutrition',
            old_name='recipe',
            new_name='recipe_for_nutirent',
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutrition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipenutrition'),
        ),
    ]
